version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '5959:5959'
    volumes:
      - ./data:/var/lib/postgresql

      environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=alex
        - POSTGRES_PASSWORD=holiday
